queue_rules:
  - name: default
    conditions:
      - check-success=Bitrise

pull_request_rules:
  - name: Resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request has conflicts when rebasing. Could you fix it @{{author}}? 🙏
  - name: Bitrise update - Auto Merge
    conditions:
      - author=github-actions[bot]
      - check-success=Bitrise
      - files=bitrise.yml
      - -files~=^(?!bitrise.yml).+$
      - head=update-br-new-xcode-version
    actions:
      review:
        type: APPROVE
        message: Github-action[bot] 💪
      queue:
        method: rebase
        name: default
  - name: Rust Component Upgrade - Auto Merge
    conditions:
      - author=github-actions[bot]
      - check-success=Bitrise
      - files=Client.xcodeproj/project.pbxproj
      - files=Client.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
    actions:
      review:
        type: APPROVE
        message: Github-action[bot] 💪
      queue:
        method: rebase
        name: default
  - name: L10N - Auto Merge
    conditions:
      - author=github-actions[bot]
      - check-success=Bitrise
      - files~=^.+\.strings$
      - -files~=^(?!^.+\.strings).+$
    actions:
      review:
        type: APPROVE
        message: LGTM 😎
      queue:
        method: rebase
        name: default
  - name: Needs landing - Rebase
    conditions:
      - check-success=Bitrise
      - label=Needs Landing
      - "#approved-reviews-by>=1"
      - -draft
      - label!=Do Not Merge ⛔️
    actions:
      queue:
        method: rebase
        name: default
  - name: Needs landing - Squash
    conditions:
      - check-success=Bitrise
      - label=Needs Landing (Squash)
      - "#approved-reviews-by>=1"
      - -draft
      - label!=Do Not Merge ⛔️
    actions:
      queue:
        method: squash
        name: default
