# The configuration for the engagementNotificationFeature feature
features:
  notification-settings-feature:
    description: >
      The feature that controls the notifications menu in Settings.
    variables:
      notification-settings-feature-status:
        description: If true, we will allow user to use the the notifications menu in Settings
        type: Boolean
        default: true
    defaults:
      - channel: beta
        value: {
          "notification-settings-feature-status": true
        }
      - channel: developer
        value: {
          "notification-settings-feature-status": true
        }
