# The configuration for the settingsCoordinatorRefactor feature
features:
  settings-coordinator-refactor:
    description: >
      This feature is for managing the roll out of the settings coordinator code as part of the changes on the navigation in the app
    variables:
      enabled:
        description: >
          Enables the feature
        type: Boolean
        default: true
    defaults:
      - channel: beta
        value:
          enabled: true
      - channel: developer
        value:
          enabled: true

