---
trust-domain: mobile
treeherder:
    group-names:
        I: Docker Image Builds
        B: Builds

task-priority: highest

taskgraph:
    register: ffios_taskgraph:register
    repositories:
        mobile:
            name: "Firefox for iOS"
    cached-task-prefix: mobile.v2.firefox-ios

workers:
    aliases:
        bitrise:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'bitrise-gcp'
        images:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'images-gcp'
        misc:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux-gcp'

scriptworker:
    scope-prefix: mobile:firefox-ios:releng
